---
kind: pipeline
type: docker
name: web

steps:
- name: install
  image: node:alpine3.13
  commands:
    - npm i

- name: tests
  image: node:alpine3.13
  commands:
    - npm run tests

- name: build
  image: node:alpine3.13
  commands:
    - npm run build

- name: rsync
  image: drillster/drone-rsync
  settings:
    key:
      from_secret: rsync_key
    hosts:
      - 39.102.77.26
    source: ./dist/*
    target: /root/six
    secrets: [ rsync_key ]

- name: notice
  image: curlimages/curl
  commands:
    - | 
    curl 'https://oapi.dingtalk.com/robot/send?access_token=e214de934c9e0942042656b49a0003917b0d387d44e5a56a8780d98dc24c3414' -H 'Content-Type: application/json' -d '{"msgtype": "text","text": {"content": "deploy Drone"}}'